# Accessing and Changing Elements, Rows, Columns

In [1]:
import numpy as np

In [2]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14,]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [3]:
a.shape

(2, 7)

In [5]:
#Get a specific element:
#[row,column]
a[1,5]

np.int64(13)

In [6]:
#get specific row:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
#get a specific column position
a[:,2]

array([ 3, 10])

In [9]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
# [startindex:endindex:stepsize]
# Look into first row, loook into second column
# all the way to the 6th column.abs
# incrememnt/step by 2.
a[0, 1:6:2]

array([2, 4, 6])

In [13]:
a[1,5]  = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [18]:
a[:,2]

array([1, 2])

In [ ]:
#Following is 3d array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

'3darray[arraySet,arrayRow,Arraycolumn]]'

In [21]:
b[0,1,1]

np.int64(4)

In [23]:
#Should return 6
b[1,0,1]

np.int64(6)

In [24]:
#should return 7
b[1,1,0]

np.int64(7)

In [25]:
b[0,1,0]

np.int64(3)

In [28]:
# Get both main arrays, in those arrays get the first row, and then both columns
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [30]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
b[1,:,0]

array([5, 7])

In [33]:
b[:,1,:] = [[9,0],[8,9]]
b

array([[[1, 2],
        [9, 0]],

       [[5, 6],
        [8, 9]]])

In [35]:
#FCC Questions/test:
c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
#Replace 4rd columns of both with 20
c[:,2] = 20
c

array([[ 1,  2, 20,  4,  5],
       [ 6,  7, 20,  9, 10]])