In [1]:
import numpy as np

In [5]:
output = np.ones((5,5))

z= np.zeros((3,3))
z[1,1]= 9

output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
zout = np.zeros((7,7))
xc = np.ones((5,5))
xc[2,2] = 5
zout[1:6,1:6] = xc
zout

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### Carfule note when copying

In [ ]:
a = np.array([1,2,3])
b = a #problem: Varibale B points directly to A
b[0] = 100 #Now A = 100 instead of B


array([100,   2,   3])

#Copy fix below

In [ ]:
a = np.array([1,2,3])
b = a.copy() 
b[0] = 100 


array([1, 2, 3])