In [1]:
import numpy as np

In [ ]:
#All Zeros matrix
#Create an array of zeros (2 of them)
# 4 rows of zeros need to be made
# 6 columns  per 4 rows in each array.
np.zeros([2,4,6])

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [4]:
np.ones([2,4,6], dtype='int32')

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int32)

In [8]:
#any other numbers custom numbers
a = np.full([2,4,6],13, dtype='float16')
a

array([[[13., 13., 13., 13., 13., 13.],
        [13., 13., 13., 13., 13., 13.],
        [13., 13., 13., 13., 13., 13.],
        [13., 13., 13., 13., 13., 13.]],

       [[13., 13., 13., 13., 13., 13.],
        [13., 13., 13., 13., 13., 13.],
        [13., 13., 13., 13., 13., 13.],
        [13., 13., 13., 13., 13., 13.]]], dtype=float16)

In [12]:
# full like = any other number.
# takes Basically takes shape of assigneed variable
# and now you can reuse it but with a differnet number
np.full_like(a, 5)

array([[[5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.]]], dtype=float16)

In [ ]:
#Random decimal numbers: you dont have to pass it as a tuple
np.random.rand(4,2)

array([[0.72267119, 0.08973309],
       [0.18819496, 0.6703894 ],
       [0.84088526, 0.38337538],
       [0.54277784, 0.08573888]])

In [15]:
a.shape

(2, 4, 6)

In [16]:
#random_sample() = generate a random sample/floats
#a.shape inside the parentheses should be used as the size
# for the new random sample.
np.random.random_sample(a.shape)

array([[[0.6385332 , 0.03458091, 0.1068374 , 0.16384488, 0.46532467,
         0.41324356],
        [0.61297946, 0.05386605, 0.76422832, 0.21734872, 0.76180155,
         0.27364503],
        [0.13143796, 0.94673385, 0.07963342, 0.27439071, 0.91532915,
         0.78791712],
        [0.84962965, 0.52767923, 0.17769545, 0.37643649, 0.0222742 ,
         0.2063928 ]],

       [[0.12729848, 0.74067315, 0.93068024, 0.90873401, 0.83140662,
         0.946146  ],
        [0.70769879, 0.78081126, 0.0454398 , 0.61736355, 0.10775842,
         0.89582767],
        [0.11580257, 0.68574425, 0.73123721, 0.47614644, 0.92355808,
         0.60482948],
        [0.03932857, 0.9817903 , 0.23189091, 0.07123546, 0.36498709,
         0.43422993]]])

In [ ]:
#Same as above, but we are specifically specfying the size we want
# not borrowing form another object.
np.random.rand(5,6)

array([[0.61327293, 0.19569444, 0.1060664 , 0.82238224, 0.98804712,
        0.51366843],
       [0.62447694, 0.47437675, 0.43889738, 0.83316891, 0.1713152 ,
        0.23319245],
       [0.17042359, 0.81959278, 0.5788173 , 0.98769919, 0.41648035,
        0.14801001],
       [0.3761732 , 0.98605678, 0.6790418 , 0.31225774, 0.05282015,
        0.91381583],
       [0.6072523 , 0.37790665, 0.47569854, 0.60288552, 0.18690209,
        0.11497418]])

In [ ]:
# randint(starting Number, Number limit, size=(rows,columns))
np.random.randint(5,9, size=(4,5))

array([[7, 7, 7, 7, 5],
       [5, 8, 6, 7, 5],
       [5, 8, 5, 6, 7],
       [5, 8, 5, 5, 7]], dtype=int32)

In [ ]:
#identity matrix defualt square matrix
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
#Repeasting arrays: look into numpy docs
arr = np.array([[1,2,3]])
rp  = np.repeat(arr,4, axis=0)
rp

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])