Seems like alot of math operators work

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [5]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
for x in a:
    a += 3
    print(x)

13
17
21
25
